accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logout, name='logout'),

    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('product_favorite/<int:pro_id>', views.product_favorite, name='product_favorite'),
    path('show_product_favorite/', views.show_product_favorite, name='show_product_favorite'),

]

coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name = 'cart'),
    path('remove_from_cart/<int:orderdetails_id>', views.remove_from_cart, name = 'remove_from_cart'),
    path('add_qty/<int:orderdetails_id>', views.add_qty, name = 'add_qty'),
    path('sub_qty/<int:orderdetails_id>', views.sub_qty, name = 'sub_qty'),
    path('chechout/', views.chechout, name = 'chechout'),
    path('my_order/', views.my_order, name = 'my_order'),

]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('coffee/', views.coffee, name='coffee'),

]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.products, name='products'),

    path('<int:pro_id>', views.product, name='product'),

    path('search/', views.search, name='search'),
    ]

templates/partials/_alerts.html
{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.tags}} alert-dismissible fade show" role="alert">
          <strong>
                  {% if 'danger' == msg.tags %}
                     ERROR
                  {% else %}
                    {{msg.tags|title}}
                  {% endif %}
                  : </strong>
          {{msg}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
{% load static %}


 <!--footer-->
    <footer class="pt-4 navbar-custom text-light">
      <div class="container-fluid text-center text-md-left">

        <div class="row">

          <div class="col-md-6 mt-md-0 mt-3">
            <h5 class="text-uppercase">
              <img src="{% static 'img/mycoffee.png' %}" class="img-brand" alt="My Coffee">
              My Coffee
            </h5>
            <p>Order your favorite coffee, and get it wherever you are.</p>
          </div>

          <hr class="clearfix w-100 d-md-none pb-3">

          <div class="col-md-3 mb-md-0 mb-3">

            <h5 class="text-uppercase">Delivery Service</h5>

            <ul class="list-unstyled">
              <li><a href="tel:333333333">333-333-333</a></li>
              <li><a href="tel:444333332">444-333-332</a></li>
              <li><a href="tel:555333331">555-333-331</a></li>
              <li><a href="tel:666333333">666-333-333</a></li>
            </ul>

          </div>

          <div class="col-md-3 mb-md-0 mb-3">

            <h5 class="text-uppercase">Join Us</h5>

            <ul class="list-unstyled">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">YouTube</a></li>
              <li><a href="#">Twitter</a></li>
            </ul>

          </div>

        </div>

      </div>

      <div class="text-center py-3">
        Copyright &copy; <span class="year">2019</span> My Coffee. Powered By MOHAMMED SARHAN
      </div>

    </footer>

templates/partials/_navbar.html
{% load static %}

<!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'img/mycoffee.png' %}" class="img-brand" alt="My Coffee">
            Fine Coffee
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                 {% if request.user.is_authenticated %}
              <li class="nav-item">
                  <a  href="{% url 'accounts:profile' %}" class="nav-link border border-light rounded waves-effect" >Welcome,{{request.user.username}}</a>
              </li>

              <li class="nav-item">
                  <a  href="{% url 'accounts:profile' %}" class="nav-link border border-light rounded waves-effect" >Profile</a>
              </li>


              <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Products
                </a>

                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown">

                <a class="dropdown-item" href="{% url 'products:product' pro_id=1 %}">Caffè Americano</a>
                <a class="dropdown-item" href="{% url 'products:product' pro_id=2 %}">Café Latte</a>
                <a class="dropdown-item" href="{% url 'products:product' pro_id=3 %}">Cappuccino</a>
                <a class="dropdown-item" href="{% url 'products:product' pro_id=4 %}">Espresso</a>
                <a class="dropdown-item"   href="{% url 'products:products' %}">All Products</a>

                </div>

              </li>

              <li class="nav-item">
                  <a class="nav-link" href="{% url 'orders:cart' %}">
                       <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M8 5.754a2.246 2.246 0 100 4.492 2.246 2.246 0 000-4.492zM4.754 8a3.246 3.246 0 116.492 0 3.246 3.246 0 01-6.492 0z" clip-rule="evenodd"/>
                      <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                    </svg>
                  </a>
              </li>

              <li class="nav-item">
                  <a  href="{% url 'orders:my_order' %}" class="nav-link border border-light rounded waves-effect" >Orders</a>
              </li>

              <li class="nav-item">
                  <a  href="{% url 'accounts:show_product_favorite' %}" class="nav-link border border-light rounded waves-effect" >
                   <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                    </svg>
                  </a>
              </li>

              <li class="nav-item">
                  <a  href="{% url 'accounts:logout' %}" class="nav-link border border-light rounded waves-effect" >Logout</a>
              </li>

                {% else %}
              <li class="nav-item">
                  <a  href="{% url 'accounts:signin' %}" class="nav-link border border-light rounded waves-effect" >Signin</a>
              </li>

              <li class="nav-item">
                  <a  href="{% url 'accounts:signup' %}" class="nav-link border border-light rounded waves-effect" >Signup</a>
              </li>

                {% endif %}
              <li>
                  <a class="nav-link" href="{% url 'coffee' %}">Coffee</a>
              </li>

              <li>
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>

            </ul>
            <form action="{% url 'products:products' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2 remove-outline" name="searchname" type="search" placeholder="Search" aria-label="Search">
            <div class="btn-group" role="group">
              <button class="btn btn-warning my-2 my-sm-0" type="submit">Search</button>
              <a href="{% url 'products:search' %}" class="btn btn-warning my-2 my-sm-0" type="submit">
                <svg class="bi bi-gear" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8.837 1.626c-.246-.835-1.428-.835-1.674 0l-.094.319A1.873 1.873 0 014.377 3.06l-.292-.16c-.764-.415-1.6.42-1.184 1.185l.159.292a1.873 1.873 0 01-1.115 2.692l-.319.094c-.835.246-.835 1.428 0 1.674l.319.094a1.873 1.873 0 011.115 2.693l-.16.291c-.415.764.42 1.6 1.185 1.184l.292-.159a1.873 1.873 0 012.692 1.116l.094.318c.246.835 1.428.835 1.674 0l.094-.319a1.873 1.873 0 012.693-1.115l.291.16c.764.415 1.6-.42 1.184-1.185l-.159-.291a1.873 1.873 0 011.116-2.693l.318-.094c.835-.246.835-1.428 0-1.674l-.319-.094a1.873 1.873 0 01-1.115-2.692l.16-.292c.415-.764-.42-1.6-1.185-1.184l-.291.159A1.873 1.873 0 018.93 1.945l-.094-.319zm-2.633-.283c.527-1.79 3.065-1.79 3.592 0l.094.319a.873.873 0 001.255.52l.292-.16c1.64-.892 3.434.901 2.54 2.541l-.159.292a.873.873 0 00.52 1.255l.319.094c1.79.527 1.79 3.065 0 3.592l-.319.094a.873.873 0 00-.52 1.255l.16.292c.893 1.64-.902 3.434-2.541 2.54l-.292-.159a.873.873 0 00-1.255.52l-.094.319c-.527 1.79-3.065 1.79-3.592 0l-.094-.319a.873.873 0 00-1.255-.52l-.292.16c-1.64.893-3.433-.902-2.54-2.541l.159-.292a.873.873 0 00-.52-1.255l-.319-.094c-1.79-.527-1.79-3.065 0-3.592l.319-.094a.873.873 0 00.52-1.255l-.16-.292c-.892-1.64.902-3.433 2.541-2.54l.292.159a.873.873 0 001.255-.52l.094-.319z" clip-rule="evenodd"/>
                  <path fill-rule="evenodd" d="M8 5.754a2.246 2.246 0 100 4.492 2.246 2.246 0 000-4.492zM4.754 8a3.246 3.246 0 116.492 0 3.246 3.246 0 01-6.492 0z" clip-rule="evenodd"/>
                </svg>
              </a>
            </div>

            </form>
        </div>
    </nav>