accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logout, name='logout'),

    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('product_favorite/<int:pro_id>', views.product_favorite, name='product_favorite'),
    path('show_product_favorite/', views.show_product_favorite, name='show_product_favorite'),

]

coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name = 'cart'),
    path('remove_from_cart/<int:orderdetails_id>', views.remove_from_cart, name = 'remove_from_cart'),
    path('add_qty/<int:orderdetails_id>', views.add_qty, name = 'add_qty'),
    path('sub_qty/<int:orderdetails_id>', views.sub_qty, name = 'sub_qty'),
    path('chechout/', views.chechout, name = 'chechout'),
    path('my_order/', views.my_order, name = 'my_order'),

]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('coffee/', views.coffee, name='coffee'),

]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.products, name='products'),

    path('<int:pro_id>', views.product, name='product'),

    path('search/', views.search, name='search'),
    ]

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.urls import reverse


class Company(models.Model):
    comp = models.CharField(max_length=225)

    def __str__(self):
        return self.comp

    class Meta:
        verbose_name = "company"
        verbose_name_plural = "companies"
        ordering = ['-comp']


class Category(models.Model):
    categ = models.CharField(max_length=225)
    catParent = models.ForeignKey('self', limit_choices_to={'catParent__isnull': True}, on_delete=models.CASCADE,
                                  blank=True, null=True)

    def __str__(self):
        return self.categ

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"
        ordering = ['-categ']


class Product(models.Model):
    name = models.CharField(max_length=225)
    description = models.TextField()
    price = models.FloatField()
    photo = models.ImageField(upload_to='photos/%y/%m/%d/')
    is_active = models.BooleanField(default=True)
    publish_date = models.DateTimeField()
    categ = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    comp = models.ForeignKey(Company, on_delete=models.PROTECT, null=True, blank=True)

    slug = models.SlugField(blank=True, null=True, verbose_name=_("Product URL"))  # , verbose_name=_("Product URL")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-publish_date']
        verbose_name = _("product")
        verbose_name_plural = _("products")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product', kwargs={'slug': self.slug})

products/forms.py
from django import forms
from .models import Category, Product, Company


class MycategForm(forms.ModelForm):
    class Meta:
        model = Category
        # fields='__all__'

        fields = [
            'categ',
            'catParent',

        ]
        widgets = {
            'categ': forms.TextInput(attrs={'class': 'form-control'})

        }


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        # fields='__all__'

        fields = [
            'comp',
        ]
        widgets = {
            'comp': forms.TextInput(attrs={'class': 'form-control'})
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        # fields='__all__'

        fields = [

            'name',
            'description'
            'price',
            'photo',
            'is_active',
            'publish_date',
            'categ',
            'comp',

        ]
        widgets = {

            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'id': 'price'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'is_active': forms.TextInput(attrs={'class': 'form-control'}),
            'publish_date': forms.TextInput(attrs={'class': 'form-control'}),
            'categ': forms.Select(attrs={'class': 'form-control'}),
            'comp': forms.Select(attrs={'class': 'form-control'}),
        }

products/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from products.models import Product


def products(request):
    try:
        pro = Product.objects.all()
    except Product.DoesNotExist:
        raise Http404

    name = None
    desc = None
    pfrom = None
    pto = None
    cs = None

    if 'cs' in request.GET:
        cs = request.GET['cs']
        if not cs:
            cs = 'off'

    if 'searchname' in request.GET:
        name = request.GET['searchname']
        if name:
            if cs == 'on':
                pro = pro.filter(name__contains=name)
            else:
                pro = pro.filter(name__icontains=name)

    if 'searchdesc' in request.GET:
        desc = request.GET['searchdesc']
        if desc:
            if cs == 'on':
                pro = pro.filter(description__contains=desc)
            else:
                pro = pro.filter(description__icontains=desc)

    if 'searchpricefrom' in request.GET and 'searchpriceto' in request.GET:
        pfrom = request.GET['searchpricefrom']
        pto = request.GET['searchpriceto']
        if pfrom and pto:
            if pfrom.isdigit() and pto.isdigit():
                pro = pro.filter(price__gte=pfrom, price__lte=pto)

    context = {
        'products': pro
    }

    return render(request, 'products/products.html', context)


def product(request, pro_id):
    context = {
        'pro': get_object_or_404(Product, pk=pro_id)
    }
    return render(request, 'products/product.html', context)


def search(request):
    return render(request, 'products/search.html')

templates/products/newcategory.html
{% extends 'base.html' %}

 {% block title %}| New Category{% endblock %}

{% block content %}

          <div class="row m-1 mb-3">
            <a href="#bookform" class="btn btn-primary" data-toggle="collapse">+ Add Category</a>
          </div>
           <div id="bookform" class="card card-primary collapse">
            <form method="POST" enctype="multipart/form-data"  >
            {% csrf_token %}
              <div class="card-body">
                 {{categform}} <!-- pages/views -->
                <small id='totalrente' class="form-text text-muted"></small>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Add</button>
              </div>
            </form>
          </div>

{% endblock %}

templates/products/newcompany.html
{% extends 'base.html' %}

 {% block title %}| New Company{% endblock %}

{% block content %}


          <div class="row m-1 mb-3">
            <a href="#bookform" class="btn btn-primary" data-toggle="collapse">+ Add Company</a>
          </div>
           <div id="bookform" class="card card-primary collapse">
            <form method="POST" enctype="multipart/form-data"  >
            {% csrf_token %}
              <div class="card-body">
                 {{compform}} <!-- pages/views -->
                <small id='totalrente' class="form-text text-muted"></small>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Add</button>
              </div>
            </form>
          </div>


{% endblock %}

templates/products/newproduct.html
{% extends 'base.html' %}

 {% block title %}| New Product{% endblock %}

{% block content %}

          <div class="row m-1 mb-3">
            <a href="#bookform" class="btn btn-primary" data-toggle="collapse">+ Add Product</a>
          </div>

          <div id="bookform" class="card card-primary collapse">
            <form method="POST" enctype="multipart/form-data"  >
            {% csrf_token %}
              <div class="card-body">
                 {{prdctform}} <!-- pages/views -->
                <small id='totalrente' class="form-text text-muted"></small>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Add</button>
              </div>
            </form>
          </div>



{% endblock %}

templates/products/product.html
{% extends 'base.html' %}
{% load static %}

 {% block title %}| Product Details {% endblock %}

{% block content %}



    <div class="my-form container p-5 my-5 rounded border border-warning">
        <form id="frmaddtocart" action="{% url 'orders:add_to_cart' %}">
            <h2 class="text-center">Product Details</h2>
            <hr>
       {% include 'partials/_alerts.html' %}
            <section>

                  <div class="row p-5 " >

                    <div class="card mb-3 w-100" >
                      <div class="row no-gutters">
                        <div class="col-md-4">
                          <img src="{{ pro.photo.url }}" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                          <div class="card-body">
                            <h5 class="card-title"  id="productName">{{ pro.name }}</h5>
                            <hr>
                            <p class="card-text" id="description"  >{{ pro.description }}</p>
                            <hr>
                            <p class="card-text">Current Price: <span id="price" class="bg-dark text-light rounded-circle p-2">${{ pro.price }}</span></p>
                            <hr>
                            <button type="button" class="btn btn-warning"  data-toggle="modal" data-target="#staticBackdrop">Add To Cart</button>


<!-- Modal --from bootstrap 4 -->
<div class="modal fade" id="staticBackdrop" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Select Quantity</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
                <!-- copied from sign in as lable and  button -->
                <label for="inputQTY">Quantity: </label>
                <input type="number" class="form-control" name="qty" id="inputQTY" value="1" required>
                <input type="hidden" name="pro_id" value="{{ pro.id }}">
                <input type="hidden" name="price" value="{{ pro.price }}">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="btnclose">Close</button>
        <button onclick="addtocart()" class="btn btn-primary" >confirm</button>
      </div>
    </div>
  </div>
</div>
                            <a href="{% url 'accounts:product_favorite' pro_id=pro.id %}" class="btn btn-warning text-white">
                              <svg class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                              </svg>
                            </a>
                              <hr>
                              <a href="{% url 'products:products' %}" class="btn btn-warning">All Products</a>
                               <a href="{% url 'index' %}" class="btn btn-warning text-white ">

                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                                  <path fill-rule="evenodd" d="M8 3.293l6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                                  <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                                </svg>

                                </a>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>

            </section>


        </form>

    <script>
        function addtocard(){
           document.getElementById('btnclose').click();
           document.getElementById('frmaddtocart').submit();
        }
    </script>

    </div>


{% endblock %}

templates/products/products.html
{% extends 'base.html' %}
{% load static %}

 {% block title %}| Products {% endblock %}

{% block content %}

    <div class="my-form container p-5 my-5 rounded border border-warning">
        <form>
            <h2 class="text-center">Products</h2>
            <hr>
        {% include 'partials/_alerts.html' %}
            <hr>

            <section>
                <div class="container-fluid">
                  <div class="row p-5" >
{%  for pro in products %}
                    <div>
                      <div class="card m-2" style="width: 18rem;">
                        <img src="{{ pro.photo.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">{{ pro.name }}</h5>
                          <p class="card-text text-truncate"  >{{ pro.description }}</p>
                          <a href="{% url 'products:product' pro_id=pro.id %}" class="btn btn-warning">Show Details</a>
                        </div>
                      </div>
                    </div>
{%  empty %}
 <h4 class="alert alert-warning">
    This Product isn't available , Please go to
     <a href="{% url 'products:products' %}" class="text-dark"> ALL PRODUCTS </a>
 </h4>


{%  endfor %}

                  </div>
                </div>
            </section>


        </form>

    </div>

{% endblock %}

templates/products/search.html
{% extends 'base.html' %}
{% load static %}

 {% block title %}| Advanced Search {% endblock %}

{% block content %}



    <div class="my-form container p-5 my-5 rounded border border-warning">
        <form action="{% url 'products:products' %}">
            <h2 class="text-center">Advanced Search</h2>
            <hr>

            <div class="form-group">
                <label for="inputSearchProductName">Product Name Contains</label>
                <input type="text" class="form-control" name="searchname" id="inputSearchProductName" placeholder="espresso">
            </div>

            <div class="form-group">
                <label for="inputSearchProductDescription">Product Description Contains</label>
                <input type="text" class="form-control" name="searchdesc" id="inputSearchProductDescription" placeholder="coffee">
            </div>

            <div class="form-row">

                <div class="form-group col-md-6">
                    <label for="inputSearchPrice1">Price Between</label>
                    <input type="number" class="form-control" name="searchpricefrom" id="inputSearchPrice1" placeholder="" value="5">
                </div>

                <div class="form-group col-md-6">
                    <label for="inputSearchPrice2">And</label>
                    <input type="number" class="form-control" name="searchpriceto" id="inputSearchPrice2" placeholder="" value="120">
                </div>

            </div>

            <div class="form-group">
                <div class="pretty p-svg p-curve p-jelly">
                    <input type="checkbox" name="cs" id="inputCaseSensitive" />
                    <div class="state p-warning">
                        <!-- svg path -->
                        <svg class="svg svg-icon" viewBox="0 0 20 20">
                            <path d="M7.629,14.566c0.125,0.125,0.291,0.188,0.456,0.188c0.164,0,0.329-0.062,0.456-0.188l8.219-8.221c0.252-0.252,0.252-0.659,0-0.911c-0.252-0.252-0.659-0.252-0.911,0l-7.764,7.763L4.152,9.267c-0.252-0.251-0.66-0.251-0.911,0c-0.252,0.252-0.252,0.66,0,0.911L7.629,14.566z" style="stroke: white;fill:white;"></path>
                        </svg>
                        <label>Case Sensitive</label>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-warning">Search for All</button>
        </form>

    </div>

{% endblock %}