accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logout, name='logout'),

    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('product_favorite/<int:pro_id>', views.product_favorite, name='product_favorite'),
    path('show_product_favorite/', views.show_product_favorite, name='show_product_favorite'),

]

coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name = 'cart'),
    path('remove_from_cart/<int:orderdetails_id>', views.remove_from_cart, name = 'remove_from_cart'),
    path('add_qty/<int:orderdetails_id>', views.add_qty, name = 'add_qty'),
    path('sub_qty/<int:orderdetails_id>', views.sub_qty, name = 'sub_qty'),
    path('chechout/', views.chechout, name = 'chechout'),
    path('my_order/', views.my_order, name = 'my_order'),

]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('coffee/', views.coffee, name='coffee'),

]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.products, name='products'),

    path('<int:pro_id>', views.product, name='product'),

    path('search/', views.search, name='search'),
    ]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
import datetime
from django_countries.fields import CountryField
from django.utils.text import slugify
from django.urls import reverse
from django.db.models.signals import post_save
from products.models import Product
from creditcards.models import CardNumberField,CardExpiryField,SecurityCodeField


class Order(models.Model):
    user = models.ForeignKey(User, verbose_name=_("user"), on_delete=models.CASCADE)
    order_date = models.DateTimeField(_("order date"), default=datetime.datetime.now)
    details=models.ManyToManyField(Product, through='OrderDetails')
    is_finished=models.BooleanField()
    total = 0
    items_count = 0


    def __str__(self):
        return 'User: ' + self.user.username +',Order id: '+ str(self.id)


class OrderDetails(models.Model):
    product=models.ForeignKey(Product,on_delete = models.CASCADE)
    order=models.ForeignKey(Order,on_delete = models.CASCADE)
    price=models.FloatField()
    quantity=models.IntegerField()

    def __str__(self):
        return 'User: ' + self.order.user.username +',Product: '+ self.product.name +',Order id: '+ str(self.order.id)

    class Meta:
        ordering = ['-id']


class Payment(models.Model):
    order=models.ForeignKey(Order,on_delete = models.CASCADE)
    ship_address=models.CharField(max_length = 150)
    ship_phone=models.CharField(max_length = 50)
    card_number=CardNumberField()
    expire=CardExpiryField()
    security_code=SecurityCodeField()

orders/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib import messages
from products.models import Product
from orders.models import Order
from orders.models import OrderDetails
from django.utils import timezone
from .models import Payment

def add_to_cart(request):
    if ('pro_id' in request.GET and 'price' in request.GET
    and 'qty' in request.GET and request.user.is_authenticated
    and not request.user.is_anonymous) :
        pro_id = request.GET['pro_id']
        qty = request.GET['qty']
        order=Order.objects.all().filter(user=request.user,is_finished=False)
        if not Product.objects.all().filter(id=pro_id).exists():
            return redirect('products')
        pro=Product.objects.get(id=pro_id)
        if order:
            # messages.success(request,'جاري متابعة الطلب القديم ')
            old_order = Order.objects.get(user=request.user,is_finished=False)
            if OrderDetails.objects.all().filter(order=old_order,product=pro).exists():
                orderdetails=OrderDetails.objects.get(order=old_order,product=pro)
                orderdetails.quantity +=int(qty)
                orderdetails.save()
            else:
                orderdetails=OrderDetails.objects.create(product=pro,order=old_order,price=pro.price,quantity=qty)
            messages.success(request,'Added to the Cart as  old order ')
        else:
            # messages.success(request,'جاري تنفيذ طلبك الجديد ')
            new_order=Order()
            new_order.user=request.user
            new_order.order_date=timezone.now()
            new_order.is_finished=False
            new_order.save()
            orderdetails=OrderDetails.objects.create(product=pro,order=new_order,price=pro.price,quantity=qty)
            messages.success(request,'Added to the Cart as new order ')
        return redirect('/products/' + request.GET['pro_id'])
    else:
        if 'pro_id' in request.GET:
            messages.error(request, 'You must be Logged In')
            return redirect('/products/'+request.GET['pro_id'])
        else:
            return redirect('index')


def cart(request):
    context=None
    if request.user.is_authenticated and not request.user.is_anonymous:
        if Order.objects.all().filter(user=request.user,is_finished=False):
            order=Order.objects.get(user = request.user, is_finished = False)
            orderdetails = OrderDetails.objects.all().filter(order=order)
            total=0
            for sub in orderdetails:
                total += sub.price * sub.quantity
            context={
                'order': order,
                'orderdetails': orderdetails,
                'total': total,
            }

    return render(request, 'orders/cart.html', context)


def remove_from_cart(request,orderdetails_id):
    if (request.user.is_authenticated and not request.user.is_anonymous
    and orderdetails_id):
        orderdetails=OrderDetails.objects.get(id=orderdetails_id)
        if orderdetails.order.user.id==request.user.id:
            orderdetails.delete()
    return redirect('orders:cart')


def add_qty(request,orderdetails_id):
    if (request.user.is_authenticated and not request.user.is_anonymous
    and orderdetails_id):
        orderdetails=OrderDetails.objects.get(id=orderdetails_id)
        if orderdetails.order.user.id==request.user.id:
            orderdetails.quantity += 1
            orderdetails.save()
    return redirect('orders:cart')


def sub_qty(request,orderdetails_id):
    if (request.user.is_authenticated and not request.user.is_anonymous
    and orderdetails_id):
        orderdetails=OrderDetails.objects.get(id=orderdetails_id)
        if orderdetails.order.user.id==request.user.id:
            if orderdetails.quantity >=1:
                orderdetails.quantity -=1
                orderdetails.save()
    return redirect('orders:cart')


def chechout(request):
    context=None
    ship_address=None
    ship_phone=None
    card_number=None
    security_code=None
    expire=None

    if (request.method == 'POST' and 'btnconfirm' in request.POST and 'ship_address' in request.POST
    and 'ship_phone' in request.POST and 'card_number' in request.POST and 'security_code'
    in request.POST and 'expire' in request.POST):
        ship_address = request.POST['ship_address']
        ship_phone = request.POST['ship_phone']
        card_number = request.POST['card_number']
        security_code = request.POST['security_code']
        expire = request.POST['expire']
        # بعد التأكيد على عملية الدفع
        if request.user.is_authenticated and not request.user.is_anonymous:
            if Order.objects.all().filter(user = request.user, is_finished = False):
                order = Order.objects.get(user = request.user, is_finished = False)
                payment= Payment(order = order,ship_address=ship_address,ship_phone=ship_phone,
                card_number=card_number,security_code=security_code,expire=expire)
                payment.save()
                order.is_finished=True
                order.save()
                messages.success(request, 'Your Payment has been finished')
                return redirect('products:products')
        context = {
                'ship_address' : ship_address,
                'ship_phone' : ship_phone,
                'card_number' : card_number,
                'security_code' : security_code,
                'expire' : expire,
        }
    else:
        #قبل التأكيد على عملية الدفع
        if request.user.is_authenticated and not request.user.is_anonymous:
            if Order.objects.all().filter(user = request.user, is_finished = False):
                order = Order.objects.get(user = request.user, is_finished = False)
                orderdetails = OrderDetails.objects.all().filter(order = order)
                total = 0
                for sub in orderdetails:
                    total += sub.price * sub.quantity
                context = {
                    'order': order,
                    'orderdetails': orderdetails,
                    'total': total,
                }

    return render(request, 'orders/chechout.html',context)


def my_order(request):
    context=None
    all_orders=None
    if request.user.is_authenticated and not request.user.is_anonymous:
        all_orders = Order.objects.all().filter(user=request.user)
        if all_orders:
                for x in all_orders:
                    order=Order.objects.get(id=x.id)
                    orderdetails = OrderDetails.objects.all().filter(order=order)
                    total=0
                    for sub in orderdetails:
                        total += sub.price * sub.quantity
                    x.total=total
                    x.items_count=orderdetails.count
    context = {'all_orders': all_orders}
    return render(request, 'orders/my_order.html', context)

templates/orders/cart.html
{% extends 'base.html' %}

{% load static %}

{% block title %}| Cart {% endblock %}

{% block content %}



    <div class="my-content container p-5 my-5 rounded border border-warning">
        <h2 class="text-center">Cart</h2>
        <hr>
        {% if not request.user.is_authenticated and  request.user.is_anonymous %}
        <h4 class="alert alert-danger">
            You must be
            <a class="text-dark" href="{% url 'accounts:signin' %}"> Logged In </a>
        </h4>
        {% elif order %}
      <h5>
        Full Name: <span class="my_num"> {{order.user.first_name |add:' '|add:order.user.last_name}}</span>
        <a href="{% url 'products:products' %} " class="btn btn-outline-warning float-right m-1">Continue Shopping</a>
        <a href="{% url 'orders:chechout' %} " class="btn btn-outline-warning float-right m-1">Checkout</a>
      </h5>
          <hr>
        Order Number: <span class="my_num"> {{order.id}} </span>
        with Total : <span class="my_num"> ${{ total|floatformat:2 }}</span>
        for : <span class="my_num"> {{orderdetails.count}}</span>  Items
        <hr>

        <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">product Name</th>
      <th scope="col">Image</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Sub Total</th>
      <th scope="col">Control</th>
    </tr>
  </thead>
  <tbody>
{%  for line in orderdetails %}
    </tr>
      <th scope="row">{{ forloop.counter}}</th>
      <td >{{ line.product.name }}</td>
      <td ><img src="{{ line.product.photo.url }}" style="width:80px; height:80px," alt=""></td>
      <td >
          <a href="{% url 'orders:add_qty' orderdetails_id=line.id %}"
          class="btn btn-outline-danger btn-sm">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-up-fill" viewBox="0 0 16 16">
          <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
          </svg>
          </a>
          {{ line.quantity }}
          <a href="{% url 'orders:sub_qty' orderdetails_id=line.id %}"
          class="btn btn-outline-danger btn-sm">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
          <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
          </svg></a>
      </td>
      <td >${{ line.price }}</td>
      <td style="font-weight:bold; color:darkred; ">${% widthratio line.quantity 1 line.price %}</td>
      <td >
          <a href="{% url 'orders:remove_from_cart' orderdetails_id=line.id %}"
          class="btn btn-outline-danger btn-sm">Remove</a>
      </td>
    </tr>
{%  empty %}
        <h5 class="alert alert-warning">
            Your cart is empty, Please go to
            <a class="dropdown-item"  href="{% url 'products:products' %}">All Products</a>
        </h5>
{% endfor %}
  </tbody>
</table>
        {% else %}
        <h4 class="alert alert-warning">
            There is no Orders, Please go to
            <a class="dropdown-item"  href="{% url 'products:products' %}">All Products</a>
        </h4>
        {% endif %}
    </div>
{% endblock %}

templates/orders/chechout.html
{% extends 'base.html' %}

 {% block title %}| Chechout {% endblock %}

{% block content %}
<div class="my-form container p-5 my-5 rounded border border-warning">
        <h2 class="text-center">Chechout</h2>
        <hr>
        {% include 'partials/_alerts.html' %}
        {% if not request.user.is_authenticated and  request.user.is_anonymous %}
            <h4 class="alert alert-warning">
                You must be
                <a class="text-dark" href="{% url 'accounts:signin' %}"> Logged In </a>
            </h4>
        {% elif not order %}
            <h4 class="alert alert-warning">
                You don't have any Orders
            </h4>
        {% else %}
         {% endif %}

        {% if is_added == True %}
        <form method="POST" style="display:none;">
        </form>
        {% else %}
        <form method="POST">
        {% endif %}
          {% csrf_token %}

        <hr>
        Order Number: <span class="my_num"> {{order.id}} </span>
        with Total : <span class="my_num"> ${{ total|floatformat:2 }}</span>
        for : <span class="my_num"> {{orderdetails.count}}</span>  Items
        <hr>
        <a href="{% url 'orders:cart' %}  " class="btn btn-secondary">Cart Details</a>
        <hr>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputship_address">Shipping Address</label>
                    <input type="text" class="form-control" name="ship_address" id="inputship_address" placeholder=" Egypt Mansoura 15-Jomhoria St." required value="{{ship_address}}">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputship_phone">Shipping Phone</label>
                    <input type="text" class="form-control" name="ship_phone" id="inputship_phone" placeholder="0030 3333 333" required value="{{ship_phone}}">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputcard_number">Card Number</label>
                    <input type="text" class="form-control" name="card_number" id="inputcard_number" placeholder="3333 3333 3333 3333" required value="{{card_number}}">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputexpire">Expire</label>
                    <input type="text" class="form-control" name="expire" id="inputexpire" placeholder="MM/YY" required value="{{expire}}">
                </div>
                <div class="form-group col-md-2">
                    <label for="inputsecurity_code">Security Code</label>
                    <input type="text" class="form-control" name="security_code" id="inputsecurity_code" placeholder="333" required value="{{security_code}}">
                </div>
            </div>
            <button type="submit" name="btnconfirm" class="btn btn-warning">Confirm</button>
        </form>

    </div>

{% endblock %}

templates/orders/my_order.html
{% extends 'base.html' %}

{% block title %}| My Orders {% endblock %}

{% block content %}

    <div class="my-content container p-5 my-5 rounded border border-warning">
        <h2 class="text-center">My Orders</h2>
        <hr>
        {% if not request.user.is_authenticated and  request.user.is_anonymous %}
        <h4 class="alert alert-danger">
            You must be
            <a class="text-dark" href="{% url 'signin' %}"> Logged In </a>
        </h4>
        {% elif all_orders %}

                    {% if all_orders.count > 0 %}
                    <h4 class="alert alert-danger">
                    You already have {{ order.count }} Orders
                    </h4>
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th scope="col">Order Number</th>
                          <th scope="col">Date</th>
                          <th scope="col">No. of Items</th>
                          <th scope="col">Total</th>
                          <th scope="col">Is Finished</th>
                        </tr>
                      </thead>
                     <tbody>
                    {%  endif %}
                    {% for order in all_orders %}
                      </tr>
                          <td >{{ order.id}}</td>
                          <td >{{ order.order_date}}</td>
                          <td >{{ order.items_count }}</td>
                          <td >${{ order.total|floatformat:2}}</td>
                          <td >
                            {% if order.is_finished == True %}
                             Yes
                            {% else %}
                             No
                            {% endif %}

                          </td>
                      </tr>
                    {%  endfor %}
                     </tbody>
                    </table>
        {% else %}
        <h4 class="alert alert-warning">
             Your cart is empty,Please go to
            <a class="dropdown-item"  href="{% url 'products:products' %}">All Products</a>
        </h4>
        {% endif %}
    </div>
{% endblock %}